[pytest]
addopts = --headed --browser chromium --html=reports/report.html --self-contained-html
testpaths = tests --slowmo=200


;[pytest]
;addopts = --headed --browser chromium --alluredir=reports/allure-results
;testpaths = tests

# Below command to convert allure json files into allure report
# allure serve reports/allure-results

